version: "3.9"

services: 
  db:
    image: postgres:15
    container_name: flask-postgres-db
    environment:  
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTRGRES_DB: ${POSTRGRES_DB}
    ports: 
      - "${POSTGRES_PORT}:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - flask-network

  app:
    build: 
      context: .
      dockerfile: Dockerfile  
    container_name: flask_app
    env_file: 
      - .env
    depends_on:
      - db
    ports: 
      - "5000:5000"
    volumes:
      - flask_data:/app
    networks:
      - flask-network
 
volumes:
  flask_data:
  postgres_data:

networks:  
  flask-network:
    driver: bridge
